// Batch engine: the thin coordinator. It plans a task graph, creates one
// worktree per task, and launches a durable background converge job per runnable
// task. It owns NO execution -- the loop/audit/cancellation live in the job and
// loop/audit stores it references by id. All side effects (worktrees, jobs) are
// injected as deps, so the scheduling/reconciliation logic is unit-testable
// without touching real git or spawning workers.
//
// No daemon: progress happens only at explicit tool calls. start launches the
// first wave; advance reconciles finished jobs and launches the next wave;
// describe is READ-ONLY (never launches or mutates); cancel stops active jobs.

import type { JobRecord, LoopJobRecord } from "../jobs/types.ts";
import { repoKey } from "../loops/location.ts";
import { planTasks, resolveManifestPath, type TaskInput } from "./plan.ts";
import { deriveBatchStatus, isBlocked, isStartable, selectRunnable } from "./schedule.ts";
import type { BatchStore } from "./store.ts";
import {
	type Batch,
	type BatchTask,
	MAX_PARALLEL_CAP,
	type TaskResult,
	type TaskStatus,
} from "./types.ts";
import { type GitRunner, repoToplevel, resolveBaseSha, WorktreeError } from "./worktree.ts";

export class BatchEngineError extends Error {}

export interface LaunchJobParams {
	cwd: string; // the task's worktree
	scope: string;
	task: string; // the task body (the converge implementer's brief)
	loopId: string;
	manifestPath?: string;
	maxIterations: number;
}

// Everything the engine touches that has a side effect or reads external state,
// injected so tests can drive it deterministically.
export interface BatchEngineDeps {
	git: GitRunner; // read-only repo queries (toplevel, base sha resolution)
	// Create the task's isolated worktree + branch off baseSha (real: a wrapper
	// over createTaskWorktree with realGit). Injected separately from `git` so the
	// fs-touching step is faked in tests. Throws WorktreeError on failure.
	createWorktree: (
		repo: string,
		batchId: string,
		taskId: string,
		baseSha: string,
	) => { worktreePath: string; branch: string };
	// Launch a background converge job in the task's worktree; returns its ids.
	launchJob: (p: LaunchJobParams) => { jobId: string; loopId: string };
	// Read a durable job record (real: JobStore.get).
	getJob: (jobId: string) => JobRecord | undefined;
	// Request cancellation of a job (real: the chit_job_cancel path).
	cancelJob: (jobId: string) => void;
	// Whether a running job's worker is gone/silent (real: isStale(job, now)).
	isStale: (job: JobRecord) => boolean;
	// The latest loop iteration's changed files / workspace warnings for a task's
	// worktree (real: read the loop log). Empty when no iteration ran.
	loopDetail: (
		worktreePath: string,
		loopId: string,
	) => {
		changedFiles: string[];
		workspaceWarnings: string[];
	};
	// Remove a task's worktree + branch (real: removeTaskWorktree with realGit).
	// Injected so cleanup is testable without touching real git/fs. Only called by
	// cleanupBatch, only for terminal tasks, only under an explicit confirm.
	removeWorktree?: (
		repo: string,
		worktreePath: string,
		branch: string,
	) => { ok: true } | { ok: false; error: string };
	now: () => number; // epoch ms
}

const DEFAULT_MAX_ITERATIONS = 3;

function iso(ms: number): string {
	return new Date(ms).toISOString();
}

export interface StartBatchOptions {
	id: string; // generated by the caller (uuid)
	cwd: string; // any path in the target repo
	tasks: TaskInput[];
	maxParallel: number;
	baseBranch?: string; // default: the repo's current HEAD
	manifestPath?: string; // batch-level default converge manifest
	maxIterations?: number;
}

// Create the batch, persist it, and launch the initial runnable wave.
export function startBatch(
	store: BatchStore,
	deps: BatchEngineDeps,
	opts: StartBatchOptions,
): Batch {
	const tasks = planTasks(opts.tasks); // throws PlanError on a bad graph
	const repo = repoToplevel(deps.git, opts.cwd);
	const baseBranch = opts.baseBranch ?? "HEAD";
	const baseSha = resolveBaseSha(deps.git, repo, baseBranch);
	const maxParallel = Math.max(1, Math.min(opts.maxParallel, MAX_PARALLEL_CAP));
	const maxIterations = opts.maxIterations ?? DEFAULT_MAX_ITERATIONS;

	const now = iso(deps.now());
	const batch: Batch = {
		schema: 1,
		id: opts.id,
		repo,
		repoKey: repoKey(opts.cwd), // informational; the store keys its path by this too
		baseBranch,
		baseSha,
		maxParallel,
		...(opts.manifestPath !== undefined && { manifestPath: opts.manifestPath }),
		status: "planning",
		tasks,
		createdAt: now,
		updatedAt: now,
	};
	store.create(batch);

	// Launch the first wave, then persist the resulting state.
	return store.update(opts.id, (c) => launchWave(c, deps, maxIterations));
}

// Reconcile finished jobs into task state, then launch the next runnable wave.
// The only progression trigger besides start. Returns the updated batch.
export function advanceBatch(
	store: BatchStore,
	deps: BatchEngineDeps,
	id: string,
	maxIterations = DEFAULT_MAX_ITERATIONS,
): Batch {
	const existing = store.get(id);
	if (!existing) throw new BatchEngineError(`no batch ${JSON.stringify(id)}`);
	if (existing.status === "cancelled") return existing;
	return store.update(id, (c) => launchWave(reconcile(c, deps), deps, maxIterations));
}

// Cancel every active job and close the batch. Pending tasks become cancelled;
// a running task's job is asked to cancel and the task is marked cancelled (its
// job settles cleanly in the background).
export function cancelBatch(store: BatchStore, deps: BatchEngineDeps, id: string): Batch {
	const existing = store.get(id);
	if (!existing) throw new BatchEngineError(`no batch ${JSON.stringify(id)}`);
	return store.update(id, (c) => {
		for (const t of c.tasks) {
			if (t.status === "running" && t.jobId) {
				try {
					deps.cancelJob(t.jobId);
				} catch {
					// best effort; the persisted intent (task cancelled) still stands
				}
				t.status = "cancelled";
			} else if (t.status === "pending") {
				t.status = "cancelled";
			}
		}
		c.status = "cancelled";
		c.updatedAt = iso(deps.now());
		return c;
	});
}

// One task's entry in a cleanup plan/result: what worktree + branch it has, the
// changed files that removal would discard, and (after confirm) whether removal
// succeeded.
export interface CleanupTaskEntry {
	id: string;
	status: TaskStatus;
	worktreePath?: string;
	branch?: string;
	changedFiles: string[]; // the diff that removal discards (from the loop record)
	removed?: boolean;
	error?: string;
}

export interface CleanupResult {
	batch_id: string;
	confirmed: boolean; // false = dry run (nothing removed)
	removable: CleanupTaskEntry[]; // terminal tasks with a worktree
	skipped: Array<{ id: string; status: TaskStatus; reason: string }>;
	receiptsKept: true; // cleanup never deletes batch/job/loop/audit records
	note: string;
}

// Retire a batch's worktrees + branches. SAFETY: refuses while any task is
// still running (a live worker is in that worktree); only ever removes worktrees
// for TERMINAL tasks (review_ready / failed / cancelled). Default is a DRY RUN
// (confirm=false): it reports exactly which worktrees/branches would be removed
// and which changed-file diffs that would discard, and removes nothing. With
// confirm=true it removes them via deps.removeWorktree. It NEVER deletes the
// batch/job/loop/audit receipts; those stay as proof history. Idempotent: a
// task whose worktree is already gone is reported removed with no error.
export function cleanupBatch(
	store: BatchStore,
	deps: BatchEngineDeps,
	id: string,
	opts: { confirm: boolean },
): CleanupResult {
	const existing = store.get(id);
	if (!existing) throw new BatchEngineError(`no batch ${JSON.stringify(id)}`);
	// Refuse cleanup while any task's WORKER is still alive. Checking task.status
	// alone is not enough: cancelBatch marks a task "cancelled" but only SIGTERMs
	// the worker -- it does not wait for exit -- so a cancelled task's worker may
	// still be mid-iteration in its worktree. A task is safe to clean only when it
	// has no live job: its job is terminal or stale (jobIsSettleable), or it never
	// launched (no jobId). Removing a worktree from under a live worker would
	// corrupt the in-flight run.
	const alive = existing.tasks.filter((t) => {
		if (!t.jobId) return false;
		const job = deps.getJob(t.jobId);
		return job !== undefined && !jobIsSettleable(job, deps);
	});
	if (alive.length > 0) {
		throw new BatchEngineError(
			`batch ${JSON.stringify(id)} still has live worker(s) for task(s): ${alive
				.map((t) => t.id)
				.join(", ")}. Cancel (chit_batch_cancel) and wait for them to settle before cleaning up.`,
		);
	}

	const removable: CleanupTaskEntry[] = [];
	const skipped: CleanupResult["skipped"] = [];
	for (const t of existing.tasks) {
		if (!t.worktreePath || !t.branch) {
			// pending/never-launched tasks have no worktree to clean
			skipped.push({ id: t.id, status: t.status, reason: "no worktree (task never launched)" });
			continue;
		}
		removable.push({
			id: t.id,
			status: t.status,
			worktreePath: t.worktreePath,
			branch: t.branch,
			changedFiles: t.result?.changedFiles ?? [],
		});
	}

	if (!opts.confirm) {
		return {
			batch_id: id,
			confirmed: false,
			removable,
			skipped,
			receiptsKept: true,
			note:
				removable.length === 0
					? "dry run: no worktrees to remove. Pass confirm=true to mark the batch cleaned."
					: `dry run: would remove ${removable.length} worktree(s) + branch(es), discarding the listed changed-file diffs. Receipts (batch/job/audit) are kept. Pass confirm=true to remove.`,
		};
	}

	const remove = deps.removeWorktree;
	if (!remove) throw new BatchEngineError("cleanup not available: no worktree remover configured");
	for (const entry of removable) {
		if (!entry.worktreePath || !entry.branch) continue;
		// Run git from the main repo (existing.repo), never from the worktree being
		// removed (git refuses to remove the current working tree).
		const r = remove(existing.repo, entry.worktreePath, entry.branch);
		entry.removed = r.ok;
		if (!r.ok) entry.error = r.error;
	}
	const failed = removable.filter((e) => e.removed === false).length;
	// Stamp cleanedAt only when every removal succeeded, so the field's meaning
	// ("the worktrees/branches were removed") stays honest. A partial failure
	// leaves cleanedAt unset; the result note + per-entry errors report it, and a
	// re-run (idempotent) can retire the stragglers.
	if (failed === 0) {
		store.update(id, (c) => ({ ...c, cleanedAt: iso(deps.now()), updatedAt: iso(deps.now()) }));
	}

	return {
		batch_id: id,
		confirmed: true,
		removable,
		skipped,
		receiptsKept: true,
		note:
			failed === 0
				? `removed ${removable.length} worktree(s) + branch(es); batch/job/audit receipts kept.`
				: `removed ${removable.length - failed} of ${removable.length}; ${failed} failed (see per-task error). Receipts kept.`,
	};
}

// --- internal: reconcile + launch (pure over the batch + deps) ----------

// Fold each running task's current job state into its task status. A job that
// reached a terminal state (or whose worker is stale) settles the task.
function reconcile(c: Batch, deps: BatchEngineDeps): Batch {
	for (const t of c.tasks) {
		if (t.status !== "running" || !t.jobId) continue;
		const job = deps.getJob(t.jobId);
		if (!job) {
			// The job record vanished; treat as failed so the batch does not hang.
			settleTask(t, "failed", deps, { failure: "job record not found" });
			continue;
		}
		if (job.policy !== "loop") {
			// A batch task always launches a loop (converge) run, so a non-loop job
			// here is an invariant violation, not a real outcome. Settle it failed
			// rather than misreport convergence fields a one-shot run does not have.
			settleTask(t, "failed", deps, { failure: "batch task job is not a loop run" });
			continue;
		}
		// `job` is a LoopJobRecord from here (the batch only runs loop policy).
		// A queued OR running job is still in flight: leave the task running UNLESS
		// the worker is gone/silent (isStale covers both a queued worker that never
		// started and a running worker that went dark). A just-launched queued job is
		// NOT a failure, so an immediate advance after start must not settle it.
		const inFlight = job.state === "queued" || job.state === "running";
		if (inFlight) {
			if (deps.isStale(job)) {
				settleTask(t, "failed", deps, { job, failure: "worker appears dead (stale job)" });
			}
			continue; // still working (or just settled stale); nothing more to do
		}
		// Terminal job states. converged is the only clean outcome (review_ready). A
		// COMPLETED-but-not-converged run -- the reviewer blocked, approved-but-
		// unverified (needs-decision), or ran out of iterations (max-iterations) -- is a
		// review judgment, NOT an execution failure: settle needs_attention so a human
		// decides (fix / rerun / discard) without it reading as a broken run, and
		// without satisfying any dependent (only review_ready does). Only a genuinely
		// failed run (state === "failed": the manifest threw or returned ok:false; the
		// vanished / non-loop / stale cases are handled above) settles failed.
		if (job.state === "completed") {
			settleTask(t, job.stopStatus === "converged" ? "review_ready" : "needs_attention", deps, {
				job,
			});
		} else if (job.state === "cancelled") {
			settleTask(t, "cancelled", deps, { job });
		} else {
			settleTask(t, "failed", deps, {
				job,
				failure: job.failure ?? `run failed (${job.stopStatus ?? "failed"})`,
			});
		}
	}
	return c;
}

// True when a running task's job would settle on the next advance: it reached a
// terminal state, or its worker is gone/silent (stale). A queued/running job that
// is NOT stale is still in flight and is NOT reconcilable. Shared by reconcile's
// intent and describe's nextAction so status and advance agree.
function jobIsSettleable(job: JobRecord, deps: BatchEngineDeps): boolean {
	if (job.state === "queued" || job.state === "running") return deps.isStale(job);
	return true; // completed / cancelled / failed
}

function settleTask(
	t: BatchTask,
	status: Extract<TaskStatus, "review_ready" | "needs_attention" | "failed" | "cancelled">,
	deps: BatchEngineDeps,
	extra: { job?: LoopJobRecord; failure?: string },
): void {
	t.status = status;
	// Loop detail comes from an actual loop job's loop log (keyed by its loopId).
	// With no loop job in hand (the record vanished, or a non-loop job was
	// rejected upstream), there is no loop detail to read.
	const detail =
		t.worktreePath && extra.job ? deps.loopDetail(t.worktreePath, extra.job.loopId) : undefined;
	const result: TaskResult = {
		iterations: extra.job?.iterationsCompleted ?? 0,
		changedFiles: detail?.changedFiles ?? [],
		workspaceWarnings: detail?.workspaceWarnings ?? [],
		auditRefs: extra.job?.auditRefs ?? [],
	};
	if (extra.job?.stopStatus !== undefined) result.stopStatus = extra.job.stopStatus;
	if (extra.job?.lastVerdict !== undefined) result.lastVerdict = extra.job.lastVerdict;
	t.result = result;
	if (status === "failed" && extra.failure !== undefined) t.error = extra.failure;
}

// Launch the next runnable wave: create a worktree + job per selected task,
// flipping it to running. Mutates and re-derives the batch status.
function launchWave(c: Batch, deps: BatchEngineDeps, maxIterations: number): Batch {
	if (c.status === "cancelled") return c;
	const runnable = selectRunnable(c);
	for (const task of runnable) {
		const t = c.tasks.find((x) => x.id === task.id);
		if (!t) continue;
		try {
			const { worktreePath, branch } = deps.createWorktree(c.repo, c.id, t.id, c.baseSha);
			// Record the worktree+branch IMMEDIATELY, before launching the job. If
			// launchJob then fails, the task is failed but its worktree is still
			// recorded, so cleanup can find and remove it (otherwise the worktree is
			// orphaned on disk with no reference).
			t.worktreePath = worktreePath;
			t.branch = branch;
			// Globally-unique loop id: the worker's loop LOCK is global by loop id
			// (jobs/locks/<loopId>.lock), so a bare task id like "docs" would collide
			// with the same task id in another batch. The batch uuid namespaces it.
			const loopId = `${c.id}-${t.id}`;
			const { jobId } = deps.launchJob({
				cwd: worktreePath,
				scope: `batch-${c.id}-${t.id}`,
				task: t.body,
				loopId,
				...(resolveManifestPath(t, c.manifestPath) !== undefined && {
					manifestPath: resolveManifestPath(t, c.manifestPath),
				}),
				maxIterations,
			});
			t.jobId = jobId;
			t.status = "running";
		} catch (e) {
			// A worktree or launch failure fails just this task; the batch goes on.
			// worktreePath/branch (if the worktree was created) stay recorded so
			// cleanup can still retire it.
			t.status = "failed";
			t.error = e instanceof WorktreeError ? e.message : (e as Error).message;
		}
	}
	c.status = deriveBatchStatus(c);
	c.updatedAt = iso(deps.now());
	return c;
}

// --- read-only describe (the join; NEVER launches or mutates) --------------

export interface BatchTaskView {
	id: string;
	title: string;
	status: TaskStatus;
	dependencies: string[];
	branch?: string;
	worktreePath?: string;
	run_id?: string; // the durable background run advancing this task (run_id == its job id)
	// Live run state for a running task, or the recorded result for a terminal one.
	runState?: JobRecord["state"] | "stale";
	phase?: JobRecord["phase"];
	stopStatus?: TaskResult["stopStatus"];
	lastVerdict?: TaskResult["lastVerdict"];
	changedFiles?: string[];
	workspaceWarnings?: string[];
	auditRefs?: string[];
	error?: string;
}

export interface BatchView {
	batch_id: string;
	repo: string;
	baseBranch: string;
	baseSha: string;
	maxParallel: number;
	status: Batch["status"];
	tasks: BatchTaskView[];
	runnableCount: number;
	nextAction: string;
	createdAt: string;
	updatedAt: string;
}

// Does the batch have a running task whose job would settle on the next advance
// (terminal or stale)? Shared by describeBatch's nextAction and chit_wait so
// status, advance, and wait all agree on "is there reconcilable work."
export function anyReconcilable(c: Batch, deps: BatchEngineDeps): boolean {
	return c.tasks.some((t) => {
		if (t.status !== "running" || !t.jobId) return false;
		const job = deps.getJob(t.jobId);
		// A VANISHED job record (undefined) is reconcilable too: reconcile() settles it
		// to failed so the batch never hangs. The predicate must match that, or
		// batchWaitState reports "working" while advanceBatch would actually do work.
		return job === undefined || jobIsSettleable(job, deps);
	});
}

// The wait-state of a batch for chit_wait. "terminal": the batch has settled (no
// task active or startable -- ready_for_review / failed / cancelled / needs_human),
// nothing left to advance. "needs_advance": chit_batch_advance would do real work
// now -- a runnable task can launch, or a finished/staled job can be reconciled.
// "working": tasks are in flight and the next advance would do nothing yet.
export function batchWaitState(
	c: Batch,
	deps: BatchEngineDeps,
): "terminal" | "needs_advance" | "working" {
	if (deriveBatchStatus(c) !== "running") return "terminal";
	if (selectRunnable(c).length > 0 || anyReconcilable(c, deps)) return "needs_advance";
	return "working";
}

// Read-only join of batch state + live job state. Computes how many tasks
// would launch on the next advance, but launches NOTHING. Inspection is safe.
export function describeBatch(c: Batch, deps: BatchEngineDeps): BatchView {
	const tasks: BatchTaskView[] = c.tasks.map((t) => {
		const view: BatchTaskView = {
			id: t.id,
			title: t.title,
			status: t.status,
			dependencies: t.dependencies,
			...(t.branch !== undefined && { branch: t.branch }),
			...(t.worktreePath !== undefined && { worktreePath: t.worktreePath }),
			...(t.jobId !== undefined && { run_id: t.jobId }),
		};
		if (t.status === "running" && t.jobId) {
			const job = deps.getJob(t.jobId);
			if (job) {
				view.runState = job.state === "running" && deps.isStale(job) ? "stale" : job.state;
				if (job.phase !== undefined) view.phase = job.phase;
			}
		}
		if (t.result) {
			if (t.result.stopStatus !== undefined) view.stopStatus = t.result.stopStatus;
			if (t.result.lastVerdict !== undefined) view.lastVerdict = t.result.lastVerdict;
			view.changedFiles = t.result.changedFiles;
			view.workspaceWarnings = t.result.workspaceWarnings;
			view.auditRefs = t.result.auditRefs;
		}
		if (t.error !== undefined) view.error = t.error;
		return view;
	});

	// How many would launch on the next advance: runnable now, accounting for
	// claim-overlap and free slots (selectRunnable), PLUS reconciliation could free
	// slots, so this is a lower bound shown to the operator.
	const runnable = selectRunnable(c);
	const reconcilable = anyReconcilable(c, deps);
	const startableBlocked = c.tasks.filter((t) => isStartable(t, c)).length;
	const blocked = c.tasks.filter((t) => isBlocked(t, c)).length;

	// Every terminal state shares one close-out instruction. Naming the next tool
	// call matters: an agent follows nextAction literally, and the old bare "review
	// the task worktrees" wording (no audit/cleanup pointer) led one to wrongly tell
	// a user to pass the batch_id to chit_audit_show -- receipts open by audit_ref, a
	// different handle. So spell out: the work is uncommitted, receipts open by
	// audit_ref, worktrees retire with chit_batch_cleanup.
	const reviewAndRetire =
		"Review the uncommitted changes in each completed task's worktree (changedFiles lists them; nothing is committed or merged), open a task's receipt with chit_audit_show { audit_ref } (each task lists its auditRefs), and retire the worktrees with chit_batch_cleanup when done.";

	let nextAction: string;
	if (c.status === "cancelled") {
		nextAction = `batch cancelled (running jobs settle in the background; worktrees are kept for inspection). ${reviewAndRetire}`;
	} else if (c.status === "ready_for_review") {
		nextAction = `all tasks terminal. ${reviewAndRetire}`;
	} else if (c.status === "failed") {
		nextAction = `batch failed; one or more tasks did not converge (see each task's status/error). ${reviewAndRetire}`;
	} else if (c.status === "needs_human") {
		nextAction = `${blocked} task(s) blocked by a failed/cancelled dependency; inspect them and start a fresh batch for the blocked work. ${reviewAndRetire}`;
	} else if (runnable.length > 0 || reconcilable) {
		const n = runnable.length;
		nextAction =
			reconcilable && n === 0
				? "a job finished; call chit_batch_advance to reconcile and launch newly runnable task(s)"
				: `call chit_batch_advance to launch ${n} runnable task(s)`;
	} else {
		nextAction =
			"tasks in flight; watch with chit_batch_status (read-only, never launches), then call chit_batch_advance once it reports a finished job or a runnable task (chit_batch_cancel to stop). Follow nextAction, not the per-task status, to drive the batch.";
	}
	void startableBlocked;

	return {
		batch_id: c.id,
		repo: c.repo,
		baseBranch: c.baseBranch,
		baseSha: c.baseSha,
		maxParallel: c.maxParallel,
		status: c.status,
		tasks,
		runnableCount: runnable.length,
		nextAction,
		createdAt: c.createdAt,
		updatedAt: c.updatedAt,
	};
}

// --- list (recover batch ids; compact, read-only) --------------------------

// A one-line summary per batch for the list view, so an operator who lost a
// batch id can find it again without reading state files. Counts come straight
// off the stored task statuses (no job reads), so this is cheap.
export interface BatchSummary {
	batch_id: string;
	status: Batch["status"];
	taskCount: number;
	reviewReady: number;
	failed: number;
	createdAt: string;
	updatedAt: string;
	cleanedAt?: string;
}

export function summarizeBatch(c: Batch): BatchSummary {
	const summary: BatchSummary = {
		batch_id: c.id,
		status: c.status,
		taskCount: c.tasks.length,
		reviewReady: c.tasks.filter((t) => t.status === "review_ready").length,
		failed: c.tasks.filter((t) => t.status === "failed").length,
		createdAt: c.createdAt,
		updatedAt: c.updatedAt,
	};
	if (c.cleanedAt !== undefined) summary.cleanedAt = c.cleanedAt;
	return summary;
}

// All batches for the repo, newest-created first, capped by `limit` when given.
// Read-only over the store (BatchStore.list already skips corrupt files).
export function listBatches(store: BatchStore, limit?: number): BatchSummary[] {
	const all = store.list().map(summarizeBatch);
	return limit !== undefined ? all.slice(0, limit) : all;
}
