// Campaign engine: the thin coordinator. It plans a task graph, creates one
// worktree per task, and launches a durable background converge job per runnable
// task. It owns NO execution -- the loop/audit/cancellation live in the job and
// loop/audit stores it references by id. All side effects (worktrees, jobs) are
// injected as deps, so the scheduling/reconciliation logic is unit-testable
// without touching real git or spawning workers.
//
// No daemon: progress happens only at explicit tool calls. start launches the
// first wave; advance reconciles finished jobs and launches the next wave;
// describe is READ-ONLY (never launches or mutates); cancel stops active jobs.

import type { JobRecord } from "../jobs/types.ts";
import { repoKey } from "../loops/location.ts";
import { planTasks, resolveManifestPath, type TaskInput } from "./plan.ts";
import { deriveCampaignStatus, isBlocked, isStartable, selectRunnable } from "./schedule.ts";
import type { CampaignStore } from "./store.ts";
import {
	type Campaign,
	type CampaignTask,
	MAX_PARALLEL_CAP,
	type TaskResult,
	type TaskStatus,
} from "./types.ts";
import { type GitRunner, repoToplevel, resolveBaseSha, WorktreeError } from "./worktree.ts";

export class CampaignEngineError extends Error {}

export interface LaunchJobParams {
	cwd: string; // the task's worktree
	scope: string;
	task: string; // the task body (the converge implementer's brief)
	loopId: string;
	manifestPath?: string;
	maxIterations: number;
}

// Everything the engine touches that has a side effect or reads external state,
// injected so tests can drive it deterministically.
export interface CampaignEngineDeps {
	git: GitRunner; // read-only repo queries (toplevel, base sha resolution)
	// Create the task's isolated worktree + branch off baseSha (real: a wrapper
	// over createTaskWorktree with realGit). Injected separately from `git` so the
	// fs-touching step is faked in tests. Throws WorktreeError on failure.
	createWorktree: (
		repo: string,
		campaignId: string,
		taskId: string,
		baseSha: string,
	) => { worktreePath: string; branch: string };
	// Launch a background converge job in the task's worktree; returns its ids.
	launchJob: (p: LaunchJobParams) => { jobId: string; loopId: string };
	// Read a durable job record (real: JobStore.get).
	getJob: (jobId: string) => JobRecord | undefined;
	// Request cancellation of a job (real: the chit_job_cancel path).
	cancelJob: (jobId: string) => void;
	// Whether a running job's worker is gone/silent (real: isStale(job, now)).
	isStale: (job: JobRecord) => boolean;
	// The latest loop iteration's changed files / workspace warnings for a task's
	// worktree (real: read the loop log). Empty when no iteration ran.
	loopDetail: (
		worktreePath: string,
		loopId: string,
	) => {
		changedFiles: string[];
		workspaceWarnings: string[];
	};
	now: () => number; // epoch ms
}

const DEFAULT_MAX_ITERATIONS = 3;

function iso(ms: number): string {
	return new Date(ms).toISOString();
}

export interface StartCampaignOptions {
	id: string; // generated by the caller (uuid)
	cwd: string; // any path in the target repo
	tasks: TaskInput[];
	maxParallel: number;
	baseBranch?: string; // default: the repo's current HEAD
	manifestPath?: string; // campaign-level default converge manifest
	maxIterations?: number;
}

// Create the campaign, persist it, and launch the initial runnable wave.
export function startCampaign(
	store: CampaignStore,
	deps: CampaignEngineDeps,
	opts: StartCampaignOptions,
): Campaign {
	const tasks = planTasks(opts.tasks); // throws PlanError on a bad graph
	const repo = repoToplevel(deps.git, opts.cwd);
	const baseBranch = opts.baseBranch ?? "HEAD";
	const baseSha = resolveBaseSha(deps.git, repo, baseBranch);
	const maxParallel = Math.max(1, Math.min(opts.maxParallel, MAX_PARALLEL_CAP));
	const maxIterations = opts.maxIterations ?? DEFAULT_MAX_ITERATIONS;

	const now = iso(deps.now());
	const campaign: Campaign = {
		schema: 1,
		id: opts.id,
		repo,
		repoKey: repoKey(opts.cwd), // informational; the store keys its path by this too
		baseBranch,
		baseSha,
		maxParallel,
		...(opts.manifestPath !== undefined && { manifestPath: opts.manifestPath }),
		status: "planning",
		tasks,
		createdAt: now,
		updatedAt: now,
	};
	store.create(campaign);

	// Launch the first wave, then persist the resulting state.
	return store.update(opts.id, (c) => launchWave(c, deps, maxIterations));
}

// Reconcile finished jobs into task state, then launch the next runnable wave.
// The only progression trigger besides start. Returns the updated campaign.
export function advanceCampaign(
	store: CampaignStore,
	deps: CampaignEngineDeps,
	id: string,
	maxIterations = DEFAULT_MAX_ITERATIONS,
): Campaign {
	const existing = store.get(id);
	if (!existing) throw new CampaignEngineError(`no campaign ${JSON.stringify(id)}`);
	if (existing.status === "cancelled") return existing;
	return store.update(id, (c) => launchWave(reconcile(c, deps), deps, maxIterations));
}

// Cancel every active job and close the campaign. Pending tasks become cancelled;
// a running task's job is asked to cancel and the task is marked cancelled (its
// job settles cleanly in the background).
export function cancelCampaign(
	store: CampaignStore,
	deps: CampaignEngineDeps,
	id: string,
): Campaign {
	const existing = store.get(id);
	if (!existing) throw new CampaignEngineError(`no campaign ${JSON.stringify(id)}`);
	return store.update(id, (c) => {
		for (const t of c.tasks) {
			if (t.status === "running" && t.jobId) {
				try {
					deps.cancelJob(t.jobId);
				} catch {
					// best effort; the persisted intent (task cancelled) still stands
				}
				t.status = "cancelled";
			} else if (t.status === "pending") {
				t.status = "cancelled";
			}
		}
		c.status = "cancelled";
		c.updatedAt = iso(deps.now());
		return c;
	});
}

// --- internal: reconcile + launch (pure over the campaign + deps) ----------

// Fold each running task's current job state into its task status. A job that
// reached a terminal state (or whose worker is stale) settles the task.
function reconcile(c: Campaign, deps: CampaignEngineDeps): Campaign {
	for (const t of c.tasks) {
		if (t.status !== "running" || !t.jobId) continue;
		const job = deps.getJob(t.jobId);
		if (!job) {
			// The job record vanished; treat as failed so the campaign does not hang.
			settleTask(t, "failed", deps, { failure: "job record not found" });
			continue;
		}
		// A queued OR running job is still in flight: leave the task running UNLESS
		// the worker is gone/silent (isStale covers both a queued worker that never
		// started and a running worker that went dark). A just-launched queued job is
		// NOT a failure, so an immediate advance after start must not settle it.
		const inFlight = job.state === "queued" || job.state === "running";
		if (inFlight) {
			if (deps.isStale(job)) {
				settleTask(t, "failed", deps, { job, failure: "worker appears dead (stale job)" });
			}
			continue; // still working (or just settled stale); nothing more to do
		}
		// Terminal job states:
		if (job.state === "completed" && job.stopStatus === "converged") {
			settleTask(t, "review_ready", deps, { job });
		} else if (job.state === "cancelled") {
			settleTask(t, "cancelled", deps, { job });
		} else {
			// completed-but-not-converged (blocked / max-iterations) or failed: do NOT
			// auto-proceed dependents onto un-converged work. The worktree diff is still
			// listed in the summary; the human can bump the budget and re-run.
			settleTask(t, "failed", deps, {
				job,
				failure: job.failure ?? `did not converge (${job.stopStatus ?? "failed"})`,
			});
		}
	}
	return c;
}

// True when a running task's job would settle on the next advance: it reached a
// terminal state, or its worker is gone/silent (stale). A queued/running job that
// is NOT stale is still in flight and is NOT reconcilable. Shared by reconcile's
// intent and describe's nextAction so status and advance agree.
function jobIsSettleable(job: JobRecord, deps: CampaignEngineDeps): boolean {
	if (job.state === "queued" || job.state === "running") return deps.isStale(job);
	return true; // completed / cancelled / failed
}

function settleTask(
	t: CampaignTask,
	status: Extract<TaskStatus, "review_ready" | "failed" | "cancelled">,
	deps: CampaignEngineDeps,
	extra: { job?: JobRecord; failure?: string },
): void {
	t.status = status;
	const detail =
		t.worktreePath && t.jobId
			? deps.loopDetail(t.worktreePath, jobLoopId(t, extra.job))
			: undefined;
	const result: TaskResult = {
		iterations: extra.job?.iterationsCompleted ?? 0,
		changedFiles: detail?.changedFiles ?? [],
		workspaceWarnings: detail?.workspaceWarnings ?? [],
		auditRefs: extra.job?.auditRefs ?? [],
	};
	if (extra.job?.stopStatus !== undefined) result.stopStatus = extra.job.stopStatus;
	if (extra.job?.lastVerdict !== undefined) result.lastVerdict = extra.job.lastVerdict;
	t.result = result;
	if (status === "failed" && extra.failure !== undefined) t.error = extra.failure;
}

function jobLoopId(t: CampaignTask, job?: JobRecord): string {
	return job?.loopId ?? t.id;
}

// Launch the next runnable wave: create a worktree + job per selected task,
// flipping it to running. Mutates and re-derives the campaign status.
function launchWave(c: Campaign, deps: CampaignEngineDeps, maxIterations: number): Campaign {
	if (c.status === "cancelled") return c;
	const runnable = selectRunnable(c);
	for (const task of runnable) {
		const t = c.tasks.find((x) => x.id === task.id);
		if (!t) continue;
		try {
			const { worktreePath, branch } = deps.createWorktree(c.repo, c.id, t.id, c.baseSha);
			// Globally-unique loop id: the worker's loop LOCK is global by loop id
			// (jobs/locks/<loopId>.lock), so a bare task id like "docs" would collide
			// with the same task id in another campaign. The campaign uuid namespaces it.
			const loopId = `${c.id}-${t.id}`;
			const { jobId } = deps.launchJob({
				cwd: worktreePath,
				scope: `campaign-${c.id}-${t.id}`,
				task: t.body,
				loopId,
				...(resolveManifestPath(t, c.manifestPath) !== undefined && {
					manifestPath: resolveManifestPath(t, c.manifestPath),
				}),
				maxIterations,
			});
			t.worktreePath = worktreePath;
			t.branch = branch;
			t.jobId = jobId;
			t.status = "running";
		} catch (e) {
			// A worktree or launch failure fails just this task; the campaign goes on.
			t.status = "failed";
			t.error = e instanceof WorktreeError ? e.message : (e as Error).message;
		}
	}
	c.status = deriveCampaignStatus(c);
	c.updatedAt = iso(deps.now());
	return c;
}

// --- read-only describe (the join; NEVER launches or mutates) --------------

export interface CampaignTaskView {
	id: string;
	title: string;
	status: TaskStatus;
	dependencies: string[];
	branch?: string;
	worktreePath?: string;
	jobId?: string;
	// Live job state for a running task, or the recorded result for a terminal one.
	jobState?: JobRecord["state"] | "stale";
	phase?: JobRecord["phase"];
	stopStatus?: TaskResult["stopStatus"];
	lastVerdict?: TaskResult["lastVerdict"];
	changedFiles?: string[];
	workspaceWarnings?: string[];
	auditRefs?: string[];
	error?: string;
}

export interface CampaignView {
	id: string;
	repo: string;
	baseBranch: string;
	baseSha: string;
	maxParallel: number;
	status: Campaign["status"];
	tasks: CampaignTaskView[];
	runnableCount: number;
	nextAction: string;
	createdAt: string;
	updatedAt: string;
}

// Read-only join of campaign state + live job state. Computes how many tasks
// would launch on the next advance, but launches NOTHING. Inspection is safe.
export function describeCampaign(c: Campaign, deps: CampaignEngineDeps): CampaignView {
	const tasks: CampaignTaskView[] = c.tasks.map((t) => {
		const view: CampaignTaskView = {
			id: t.id,
			title: t.title,
			status: t.status,
			dependencies: t.dependencies,
			...(t.branch !== undefined && { branch: t.branch }),
			...(t.worktreePath !== undefined && { worktreePath: t.worktreePath }),
			...(t.jobId !== undefined && { jobId: t.jobId }),
		};
		if (t.status === "running" && t.jobId) {
			const job = deps.getJob(t.jobId);
			if (job) {
				view.jobState = job.state === "running" && deps.isStale(job) ? "stale" : job.state;
				if (job.phase !== undefined) view.phase = job.phase;
			}
		}
		if (t.result) {
			if (t.result.stopStatus !== undefined) view.stopStatus = t.result.stopStatus;
			if (t.result.lastVerdict !== undefined) view.lastVerdict = t.result.lastVerdict;
			view.changedFiles = t.result.changedFiles;
			view.workspaceWarnings = t.result.workspaceWarnings;
			view.auditRefs = t.result.auditRefs;
		}
		if (t.error !== undefined) view.error = t.error;
		return view;
	});

	// How many would launch on the next advance: runnable now, accounting for
	// claim-overlap and free slots (selectRunnable), PLUS reconciliation could free
	// slots, so this is a lower bound shown to the operator.
	const runnable = selectRunnable(c);
	const anyReconcilable = c.tasks.some((t) => {
		if (t.status !== "running" || !t.jobId) return false;
		const job = deps.getJob(t.jobId);
		return job !== undefined && jobIsSettleable(job, deps);
	});
	const startableBlocked = c.tasks.filter((t) => isStartable(t, c)).length;
	const blocked = c.tasks.filter((t) => isBlocked(t, c)).length;

	let nextAction: string;
	if (c.status === "cancelled") {
		nextAction = "campaign cancelled";
	} else if (c.status === "ready_for_review") {
		nextAction = "all tasks terminal; review the task worktrees (chit_campaign_status lists them)";
	} else if (c.status === "needs_human") {
		nextAction = `${blocked} task(s) blocked by a failed/cancelled dependency; inspect and start a fresh campaign for them`;
	} else if (runnable.length > 0 || anyReconcilable) {
		const n = runnable.length;
		nextAction =
			anyReconcilable && n === 0
				? "a job finished; call chit_campaign_advance to reconcile and launch newly runnable task(s)"
				: `call chit_campaign_advance to launch ${n} runnable task(s)`;
	} else {
		nextAction = "tasks in flight; poll chit_campaign_status, or chit_campaign_cancel to stop";
	}
	void startableBlocked;

	return {
		id: c.id,
		repo: c.repo,
		baseBranch: c.baseBranch,
		baseSha: c.baseSha,
		maxParallel: c.maxParallel,
		status: c.status,
		tasks,
		runnableCount: runnable.length,
		nextAction,
		createdAt: c.createdAt,
		updatedAt: c.updatedAt,
	};
}
